const STORAGE_KEY = 'safety-sprint-state-v1';
const DEFAULT_STATE = {
  user: null,
  screen: 'login',
  activeTab: 'play',
  currentSession: null,
  results: null,
  sessions: [],
  answers: [],
  tickets: 0,
  streak: 0,
  totalPoints: 0,
  badges: [],
  importedCount: 0,
  players: [
    { nickname:'TrackBoss92', team:'South Jersey', points:4550, sessions:12, tickets:15 },
    { nickname:'SignalSam', team:'Detroit', points:4320, sessions:11, tickets:12 },
    { nickname:'RailRanger', team:'North Jersey', points:3890, sessions:9, tickets:10 },
    { nickname:'YardHawk', team:'South Jersey', points:3400, sessions:8, tickets:9 }
  ],
  questions: [
    { id:'q1', category:'Operating Rules', difficulty:'Easy', question:'You see a conflicting instruction before a move. What do you do first?', choices:['Keep moving if it seems safe','Ask someone after the move','Stop and verify before continuing','Ignore it if the crew is busy'], correct:2, explanation:'When instructions conflict, stop and clarify before continuing. Safe track first.' },
    { id:'q2', category:'PPE', difficulty:'Easy', question:'You enter a work area and notice your PPE is incomplete. What is the safe move?', choices:['Borrow later if needed','Continue for just one quick task','Stop and get the required PPE','Ask a coworker to watch you'], correct:2, explanation:'Required PPE must be in place before the task starts. No shortcut hero mode unlocked.' },
    { id:'q3', category:'Communication', difficulty:'Easy', question:'A radio message is unclear during a safety-sensitive task. What should happen next?', choices:['Guess based on routine','Repeat back and confirm','Let the movement continue','Switch to texting'], correct:1, explanation:'Clear communication matters. Repeat back, confirm, and continue only when the instruction is understood.' },
    { id:'q4', category:'Yard Safety', difficulty:'Easy', question:'You spot a potential hazard near the walking path. What is the best first action?', choices:['Step around it and forget it','Post it online','Report or correct it according to procedure','Wait for the next shift'], correct:2, explanation:'Hazards should be corrected or reported quickly so the next person does not meet the same trap.' },
    { id:'q5', category:'Fitness for Duty', difficulty:'Easy', question:'Someone appears distracted before a critical task. What is the safest response?', choices:['Ignore it to avoid drama','Check in and pause the task if needed','Tell them to hurry up','Make a joke and move on'], correct:1, explanation:'Pause, check in, and keep the task safe. A quick reset beats a bad outcome.' },
    { id:'q6', category:'Signals', difficulty:'Medium', question:'The signal or instruction does not match what you expected. What should you do?', choices:['Follow what you expected','Stop and verify before acting','Ask after the movement','Move slowly and hope'], correct:1, explanation:'Unexpected signal or instruction? Stop and verify. Green signal for good judgment.' },
    { id:'q7', category:'Securement', difficulty:'Medium', question:'Before leaving equipment, what matters most?', choices:['That the job was fast','That securement requirements are met','That the paperwork looks neat','That the weather is good'], correct:1, explanation:'Equipment securement is not optional. Meet the required procedure before leaving the area.' }
  ]
};
let state = load();
function load(){ try { return { ...DEFAULT_STATE, ...(JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}) }; } catch(e){ return structuredClone(DEFAULT_STATE); } }
function save(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function setScreen(screen){ state.screen = screen; save(); render(); }
function setTab(tab){ state.activeTab = tab; state.screen = 'home'; save(); render(); }
function el(id){ return document.getElementById(id); }
function app(html){ document.getElementById('app').innerHTML = `<div class="phone"><header class="header"><div class="brand"><div class="logo-mark">🚦</div><div><h1>Conrail Safety Sprint</h1><p>One minute. Five questions. Safer every day.</p></div></div></header>${html}</div>`; }
function nav(){ const tabs = [['play','PLAY'],['badges','BADGES'],['board','BOARD'],['profile','ME'],['admin','ADMIN']]; return `<nav class="nav">${tabs.map(([id,label])=>`<button class="${state.activeTab===id?'active':''}" onclick="setTab('${id}')">${label}</button>`).join('')}</nav>`; }
function login(){ app(`<main class="content"><section class="card hero-card big-center"><div class="train">🚂</div><h2 class="title">Locked Rail Yard</h2><p class="subtle">Use a verified @conrail.com email to enter the test yard.</p><input id="email" class="input" placeholder="name@conrail.com" value="demo.manager@conrail.com"><button class="primary" onclick="sendMagic()">SEND MAGIC LINK</button><button class="ghost" onclick="demoUnlock()">DEMO UNLOCK</button><div id="msg" class="notice">Try gmail.com to test the block, then use demo.manager@conrail.com.</div></section><section class="card"><strong>Test build note</strong><p class="small">This local prototype simulates the domain lock in the browser. Production must enforce @conrail.com server-side with Supabase Auth, SSO, or another identity provider.</p></section></main>`); }
function sendMagic(){ const email = el('email').value.trim().toLowerCase(); if(!email.endsWith('@conrail.com')) { el('msg').innerHTML='🚧 Whoa there, wrong track. Use your @conrail.com email.'; return; } el('msg').innerHTML='✅ Signal sent. In this prototype, click Demo Unlock to continue.'; }
function demoUnlock(){ const email = el('email').value.trim().toLowerCase(); if(!email.endsWith('@conrail.com')) { el('msg').innerHTML='🚧 Domain blocked. Only @conrail.com can unlock the yard.'; return; } state.user = { email, nickname:'', team:'North Jersey', role: email.includes('manager') ? 'admin':'employee' }; state.screen = 'setup'; save(); render(); }
function setup(){ app(`<main class="content"><section class="card"><h2 class="title">Build Your Crew Card</h2><label>Nickname</label><input id="nick" class="input" maxlength="20" value="Big Mike"><label>Team / Terminal</label><select id="team" class="select"><option>North Jersey</option><option>South Jersey</option><option>Detroit</option><option>Shared Assets</option><option>Training Team</option></select><label class="row" style="align-items:flex-start"><input id="consent" type="checkbox" checked style="flex:0;margin-top:4px"><span class="small">I understand this app tracks game progress for safety learning rewards and manager reporting.</span></label><button class="primary" onclick="finishSetup()">ENTER THE YARD</button></section></main>`); }
function finishSetup(){ if(!el('consent').checked) return alert('Please accept the progress tracking notice to continue.'); state.user.nickname = el('nick').value.trim() || 'Safety Sprinter'; state.user.team = el('team').value; state.screen='home'; state.activeTab='play'; save(); render(); }
function home(){ let content = ''; if(state.activeTab==='play') content = playHome(); if(state.activeTab==='badges') content = badges(); if(state.activeTab==='board') content = board(); if(state.activeTab==='profile') content = profile(); if(state.activeTab==='admin') content = admin(); app(`<main class="content">${content}</main>${nav()}`); }
function playHome(){ const level = levelInfo(); return `<section class="card hero-card big-center"><div class="train">🚂</div><h2 class="title">${state.user.nickname || 'Safety Sprinter'}</h2><span class="badge">Level ${level.level}: ${level.title}</span><div class="track"><span style="width:${level.progress}%"></span></div><div class="kpis"><div class="kpi"><strong>${state.streak}</strong><span>Day Streak</span></div><div class="kpi"><strong>${state.tickets}</strong><span>Tickets</span></div><div class="kpi"><strong>${state.totalPoints}</strong><span>Points</span></div></div><button class="primary" onclick="startSprint('daily')">START TODAY'S SPRINT</button><button class="secondary" onclick="startSprint('friday')">FRIDAY BOSS BATTLE</button></section><section class="card"><strong>Mini Missions</strong><p class="small">Tap a category for a quick practice sprint.</p><div>${['Signals','PPE','Yard Safety','Communication','Operating Rules','Securement'].map(c=>`<button class="ghost" onclick="startSprint('category','${c}')">${c}</button>`).join('')}</div></section><section class="notice">Use only during approved breaks, training time, or when directed by a supervisor. Phones down when active work is happening.</section>`; }
function levelInfo(){ const pts = state.totalPoints; const levels = [[1,'Yard Rookie',0],[2,'Track Trainee',1000],[3,'Signal Spotter',3000],[4,'Safety Switchman',6000],[5,'Rule Wrangler',10000],[6,'Blue Badge Boss',15000],[7,'Yard Legend',25000]]; let cur=levels[0], next=levels[1]; for(let i=0;i<levels.length;i++){ if(pts>=levels[i][2]) { cur=levels[i]; next=levels[i+1]||levels[i]; } } const progress = next===cur ? 100 : Math.min(100, Math.round(((pts-cur[2])/(next[2]-cur[2]))*100)); return {level:cur[0], title:cur[1], progress}; }
function shuffle(a){ return [...a].sort(()=>Math.random()-.5); }
function startSprint(mode, category){ let pool = state.questions.filter(q=>q.active!==false && (!category || q.category===category)); if(pool.length<5) pool = state.questions; const questions = shuffle(pool).slice(0, mode==='friday'?7:5); state.currentSession = { mode, category: category||null, index:0, score:0, correct:0, startedAt:Date.now(), questions, responses:[], locked:false, feedback:null }; state.screen='game'; save(); render(); }
function game(){ const s = state.currentSession; const q = s.questions[s.index]; const prog = Math.round((s.index/s.questions.length)*100); app(`<main class="content"><section class="card"><span class="badge">${s.mode==='friday'?'Friday Boss':'Daily Sprint'}</span><div class="track"><span style="width:${prog}%"></span></div><p class="small">Question ${s.index+1} of ${s.questions.length} | ${q.category}</p><h2 class="question-title">${q.question}</h2>${q.choices.map((c,i)=>`<button class="choice ${s.feedback? (i===q.correct?'good':(i===s.feedback.selected?'bad':'')) : ''}" onclick="answer(${i})" ${s.feedback?'disabled':''}>${String.fromCharCode(65+i)}. ${c}</button>`).join('')}${s.feedback?`<div class="feedback ${s.feedback.correct?'good':'bad'}"><strong>${s.feedback.correct?'✅ Green Signal!':'🚧 Red Signal!'}</strong><br>${q.explanation}<br><br>+${s.feedback.points} points</div><button class="primary" onclick="nextQuestion()">${s.index===s.questions.length-1?'SEE RESULTS':'NEXT QUESTION'}</button>`:''}</section></main>`); }
function answer(i){ const s=state.currentSession; if(!s || s.feedback) return; const q=s.questions[s.index]; const correct=i===q.correct; let pts = correct ? 100 : 0; if(correct && Math.random()>.35) pts += 50; s.score += pts; if(correct) s.correct += 1; const resp = { questionId:q.id, selected:i, correct, points:pts, category:q.category, at:Date.now() }; s.responses.push(resp); s.feedback = { selected:i, correct, points:pts }; save(); render(); }
function nextQuestion(){ const s=state.currentSession; if(s.index < s.questions.length-1){ s.index++; s.feedback=null; save(); render(); } else finishSession(); }
function finishSession(){ const s=state.currentSession; let bonus=250; let tickets=1; if(s.correct===s.questions.length){ bonus+=500; tickets+=1; } if(s.mode==='friday' && s.correct >= Math.ceil(s.questions.length*.8)){ bonus+=1000; tickets+=3; } s.score+=bonus; state.totalPoints += s.score; state.tickets += tickets; state.streak += 1; const session = { id:'s'+Date.now(), mode:s.mode, score:s.score, correct:s.correct, questionCount:s.questions.length, tickets, completedAt:new Date().toISOString(), responses:s.responses }; state.sessions.push(session); state.answers.push(...s.responses); state.results=session; state.players = state.players.filter(p=>p.nickname !== (state.user.nickname || 'Safety Sprinter'));
state.players.push({ nickname:state.user.nickname || 'Safety Sprinter', team:state.user.team, points:state.totalPoints, sessions:state.sessions.length, tickets:state.tickets }); updateBadges(); state.currentSession=null; state.screen='results'; save(); render(); }
function updateBadges(){ const count=(cat)=>state.answers.filter(a=>a.correct && (!cat || a.category===cat)).length; const earned = [];
 if(state.sessions.some(s=>s.correct===s.questionCount)) earned.push('Green Signal');
 if(count('PPE')>=5) earned.push('PPE Pro');
 if(count('Signals')>=5) earned.push('Signal Spotter');
 if(count('Yard Safety')>=5) earned.push('Yard Hawk');
 if(state.streak>=7) earned.push('Streak Engine');
 if(count()>=20) earned.push('No Shortcut Hero');
 state.badges=[...new Set([...state.badges,...earned])]; }
function results(){ const r=state.results; app(`<main class="content"><section class="card big-center"><div class="train">🏁</div><h2 class="title">Sprint Complete!</h2><div class="kpis"><div class="kpi"><strong>${r.score}</strong><span>Score</span></div><div class="kpi"><strong>${r.correct}/${r.questionCount}</strong><span>Correct</span></div><div class="kpi"><strong>+${r.tickets}</strong><span>Tickets</span></div></div><p class="subtle">${r.correct===r.questionCount?'Perfect run. Green signal all the way.':'Nice work. Review missed questions to lock it in.'}</p><button class="primary" onclick="startSprint('daily')">PLAY AGAIN</button><button class="secondary" onclick="setTab('board')">VIEW LEADERBOARD</button><button class="ghost" onclick="setTab('play')">BACK HOME</button></section></main>${nav()}`); }
function badges(){ const defs = [['Green Signal','First perfect round','🚦'],['PPE Pro','5 PPE questions correct','🦺'],['Signal Spotter','5 signal questions correct','💡'],['Yard Hawk','5 yard safety questions correct','🦅'],['Streak Engine','7-day streak','🔥'],['No Shortcut Hero','20 total correct answers','🏆']]; return `<section class="card"><h2 class="title">Badge Book</h2>${defs.map(([name,desc,icon])=>`<div class="card" style="margin:8px 0;background:${state.badges.includes(name)?'#ecfff5':'#f7fbff'}"><strong>${icon} ${name}</strong><p class="small">${desc}</p><span class="badge">${state.badges.includes(name)?'Earned':'Locked'}</span></div>`).join('')}</section>`; }
function board(){ const rows=[...state.players].sort((a,b)=>b.points-a.points); const teamMap={}; rows.forEach(p=>teamMap[p.team]=(teamMap[p.team]||0)+p.points); const teams=Object.entries(teamMap).sort((a,b)=>b[1]-a[1]); return `<section class="card"><h2 class="title">Weekly Leaderboard</h2><table class="table"><tr><th>#</th><th>Nickname</th><th>Team</th><th>Pts</th></tr>${rows.map((p,i)=>`<tr><td>${i+1}</td><td>${p.nickname}</td><td>${p.team}</td><td>${p.points}</td></tr>`).join('')}</table></section><section class="card"><h3>Team Standings</h3><table class="table"><tr><th>#</th><th>Team</th><th>Pts</th></tr>${teams.map((t,i)=>`<tr><td>${i+1}</td><td>${t[0]}</td><td>${t[1]}</td></tr>`).join('')}</table><p class="small">Leaderboard resets every Monday in production.</p></section>`; }
function profile(){ return `<section class="card"><h2 class="title">My Profile</h2><p><strong>Email:</strong> ${maskEmail(state.user.email)}</p><p><strong>Nickname:</strong> ${state.user.nickname}</p><p><strong>Team:</strong> ${state.user.team}</p><p><strong>Role:</strong> ${state.user.role}</p><div class="kpis"><div class="kpi"><strong>${state.sessions.length}</strong><span>Sprints</span></div><div class="kpi"><strong>${state.tickets}</strong><span>Tickets</span></div><div class="kpi"><strong>${state.badges.length}</strong><span>Badges</span></div></div><button class="ghost" onclick="resetDemo()">RESET DEMO DATA</button><button class="danger" onclick="logout()">LOG OUT</button></section><section class="notice">Privacy-first test app: no browsing history, no GPS, no contacts, no keystroke tracking.</section>`; }
function maskEmail(email){ const [a,b]=email.split('@'); return `${a.slice(0,1)}***@${b}`; }
function logout(){ state.user=null; state.screen='login'; save(); render(); }
function resetDemo(){ if(confirm('Reset all local demo progress?')){ localStorage.removeItem(STORAGE_KEY); state=structuredClone(DEFAULT_STATE); render(); } }
function admin(){ if(state.user.role!=='admin') return `<section class="card"><h2>Admin locked</h2><p class="small">Only manager/admin emails can view this panel in the prototype.</p></section>`; return `<section class="card admin-only"><h2 class="title">Manager Dashboard</h2><div class="kpis"><div class="kpi"><strong>${state.players.length}</strong><span>Players</span></div><div class="kpi"><strong>${state.sessions.length}</strong><span>Your Sessions</span></div><div class="kpi"><strong>${state.questions.length}</strong><span>Questions</span></div></div><button class="primary" onclick="downloadReport()">EXPORT CSV REPORT</button></section><section class="card"><h3>Import Questions</h3><p class="small">Paste CSV rows with: question,choice_a,choice_b,choice_c,choice_d,correct_answer,explanation,category,difficulty</p><textarea id="csv" rows="7" placeholder="Question,Choice A,Choice B,Choice C,Choice D,C,Explanation,Category,Easy"></textarea><button class="secondary" onclick="importCsv()">IMPORT SAMPLE CSV</button><button class="ghost" onclick="loadSampleCsv()">LOAD SAMPLE ROW</button></section>`; }
function loadSampleCsv(){ el('csv').value='You notice a tool left in a walkway. What is the safest action?,Step over it,Move or report it,Wait for someone else,Ignore it,B,Clear or report walkway hazards quickly.,Yard Safety,Easy'; }
function importCsv(){ const txt=el('csv').value.trim(); if(!txt) return alert('Paste or load a CSV row first.'); const lines=txt.split(/\n+/); let added=0; lines.forEach(line=>{ const cells=parseCsvLine(line); if(cells.length>=9){ const idx={A:0,B:1,C:2,D:3}[String(cells[5]).trim().toUpperCase()] ?? 0; state.questions.push({id:'imp'+Date.now()+Math.random(), question:cells[0], choices:[cells[1],cells[2],cells[3],cells[4]], correct:idx, explanation:cells[6], category:cells[7], difficulty:cells[8], active:true}); added++; }}); state.importedCount+=added; save(); alert(`Imported ${added} question(s).`); render(); }
function parseCsvLine(line){ const out=[]; let cur='', q=false; for(let i=0;i<line.length;i++){ const ch=line[i]; if(ch==='"'){ q=!q; } else if(ch===',' && !q){ out.push(cur.trim().replace(/^"|"$/g,'')); cur=''; } else cur+=ch; } out.push(cur.trim().replace(/^"|"$/g,'')); return out; }
function downloadReport(){ const rows=['nickname,email,team,total_points,tickets,sessions,badges',`${state.user.nickname},${state.user.email},${state.user.team},${state.totalPoints},${state.tickets},${state.sessions.length},"${state.badges.join('; ')}"`]; const blob=new Blob([rows.join('\n')],{type:'text/csv'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='safety-sprint-report.csv'; a.click(); }
function render(){ if(!state.user && state.screen!=='login') state.screen='login'; if(state.screen==='login') return login(); if(state.screen==='setup') return setup(); if(state.screen==='game') return game(); if(state.screen==='results') return results(); return home(); }
window.sendMagic=sendMagic; window.demoUnlock=demoUnlock; window.finishSetup=finishSetup; window.setTab=setTab; window.startSprint=startSprint; window.answer=answer; window.nextQuestion=nextQuestion; window.resetDemo=resetDemo; window.logout=logout; window.downloadReport=downloadReport; window.importCsv=importCsv; window.loadSampleCsv=loadSampleCsv; render();
