
const $ = (s) => document.querySelector(s);
const app = $('#app');
const LS='css-v2-state';
const ADMIN_EMAILS=['demo.manager@conrail.com','mickey.dasilva@conrail.com'];
const seedQuestions=[
 {id:'q1',question:'You see a conflicting instruction before making a move. What should you do first?',choices:['Keep moving if it looks clear','Ask about it after the move','Stop and verify the instruction','Let the crew decide later'],correct:2,explanation:'When instructions conflict, stop and clarify before continuing.',category:'Operating Rules',difficulty:'Easy',source:'Operating Rules: Conflicting Instructions',ruleId:'r1'},
 {id:'q2',question:'Before entering a work area, what is the safest first move?',choices:['Check your phone quickly','Confirm required authority/protection','Walk in if no train is visible','Wait for someone else to notice'],correct:1,explanation:'Confirm that required authority and protection are in place before entering a controlled or restricted area.',category:'Roadway Worker Protection',difficulty:'Easy',source:'Roadway Worker Protection Basics',ruleId:'r2'},
 {id:'q3',question:'A shortcut saves 30 seconds but skips a safety step. What is the green-signal choice?',choices:['Take the shortcut once','Skip it only if busy','Follow every required safety step','Ask after the task is done'],correct:2,explanation:'Shortcuts that bypass required steps can create serious risk. Follow the required procedure every time.',category:'Safety Culture',difficulty:'Easy',source:'Safety First Principles',ruleId:'r3'},
 {id:'q4',question:'You answer wrong in Safety Sprint. What should you do next?',choices:['Ignore the correction','Review the rule and try again','Blame the timer','Skip that category forever'],correct:1,explanation:'The fastest way to improve is to review the rule behind the missed question.',category:'Learning',difficulty:'Easy',source:'Rule Review Practice',ruleId:'r4'},
 {id:'q5',question:'What should the public leaderboard show?',choices:['Full email addresses','Payroll data','Nicknames and team points','Private employee records'],correct:2,explanation:'Public boards should motivate people without exposing unnecessary personal information.',category:'Privacy',difficulty:'Easy',source:'Privacy and Data Minimization',ruleId:'r5'}
];
const seedRules=[
 {id:'r1',title:'Conflicting Instructions',category:'Operating Rules',text:'When instructions conflict, the safest action is to stop, clarify, and verify before continuing. Do not guess or proceed based on assumptions.',source:'Sample Operating Rules Reference',related:['q1']},
 {id:'r2',title:'Authority and Protection Before Entry',category:'Roadway Worker Protection',text:'Before entering a controlled, restricted, or protected area, employees should confirm that the required authority, communication, and protection are in place.',source:'Sample Roadway Worker Reference',related:['q2']},
 {id:'r3',title:'No Shortcut Safety Principle',category:'Safety Culture',text:'A shortcut is not acceptable when it bypasses a required safety step. Safe work means following the required process even when the task feels routine.',source:'Sample Safety Standard',related:['q3']},
 {id:'r4',title:'Review Missed Questions',category:'Learning',text:'Missed questions should link back to the rule dictionary so employees can understand the reason, not just memorize an answer.',source:'Safety Sprint Learning Model',related:['q4']},
 {id:'r5',title:'Leaderboard Privacy',category:'Privacy',text:'Public leaderboards should use nicknames and team names. Admin views may show verified email addresses when necessary for rewards and reporting.',source:'Safety Sprint Privacy Model',related:['q5']}
];
const seedTeams=[
 {id:'t1',name:'North Jersey Rail Hawks',captain:'TrackBoss92',points:12800,members:8},
 {id:'t2',name:'South Yard Signal Sharks',captain:'YardLegend',points:11650,members:7},
 {id:'t3',name:'Detroit Blue Engines',captain:'RuleRocket',points:9900,members:6}
];
let state=load();
function defaults(){return {screen:'login',email:'',profile:null,unlocked:false,points:0,tickets:0,streak:0,badges:['Green Signal'],missed:[],sessions:0,teamsEnabled:true,team:null,teams:seedTeams,questions:seedQuestions,rules:seedRules,leaderboard:[{nick:'TrackBoss92',team:'North Jersey Rail Hawks',points:4520},{nick:'YardLegend',team:'South Yard Signal Sharks',points:4300},{nick:'RuleRocket',team:'Detroit Blue Engines',points:3980},{nick:'SignalSam',team:'North Jersey Rail Hawks',points:3400}],activeGame:null,adminMode:false,search:''}}
function load(){try{return {...defaults(),...JSON.parse(localStorage.getItem(LS)||'{}')}}catch(e){return defaults()}}
function save(){localStorage.setItem(LS,JSON.stringify(state))}
function nav(screen){state.screen=screen; save(); render()}
function isAdmin(){return state.profile && ADMIN_EMAILS.includes((state.profile.email||'').toLowerCase())}
function top(title='Conrail Safety Sprint',sub='Get the green signal.') {return `<div class="topbar"><div class="brand-row"><div class="crossbuck-mini"><span class="xbar x1"></span><span class="xbar x2"></span><span class="post"></span></div><div class="brand-text"><h1>${title}</h1><p>${sub}</p></div></div></div>`}
function tabs(){if(!state.profile)return ''; const items=[['home','🚂','Play'],['teams','👥','Teams'],['rules','📘','Rules'],['board','🏆','Board'],['profile','👤','Me']]; return `<div class="tabs">${items.map(i=>`<button class="tab ${state.screen==i[0]?'active':''}" onclick="nav('${i[0]}')"><span class="emoji">${i[1]}</span>${i[2]}</button>`).join('')}</div>`}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;document.body.appendChild(t);setTimeout(()=>t.remove(),2200)}
function login(){return `${top('Conrail Safety Sprint','Profile-locked test build')}<div class="screen"><div class="card hero"><div class="crossbuck-icon"><span class="xbar x1"></span><span class="xbar x2"></span><span class="post"></span></div><h2>Locked Rail Yard</h2><p>Only verified <b>@conrail.com</b> emails can enter this prototype.</p><label>Conrail Email</label><input id="email" type="email" value="${state.email||''}" placeholder="name@conrail.com"><button class="big-button" onclick="sendMagic()">Send Magic Link</button><button class="button secondary" style="margin-top:12px" onclick="demoUnlock()">Demo Unlock</button><div id="loginMsg"></div><p class="footer-note">For the real app, this gate should be enforced by secure backend authentication.</p></div></div>`}
window.sendMagic=()=>{state.email=$('#email').value.trim().toLowerCase();save(); const msg=$('#loginMsg'); if(!state.email.endsWith('@conrail.com')){msg.innerHTML='<div class="message error">Whoa there, wrong track. Use your @conrail.com email.</div>'}else{msg.innerHTML='<div class="message good">Green signal sent. For demo mode, tap Demo Unlock.</div>'}}
window.demoUnlock=()=>{let email=($('#email')?.value||state.email||'demo.manager@conrail.com').trim().toLowerCase(); if(!email.endsWith('@conrail.com')) email='demo.manager@conrail.com'; state.email=email; state.screen='setup'; save(); render()}
function setup(){return `${top('Build Your Crew Card','First-time profile setup')}<div class="screen"><div class="card"><label>Nickname shown on leaderboards</label><input id="nick" placeholder="Big Mike" value="${state.profile?.nick||''}"><label>Home terminal / location</label><input id="loc" placeholder="North Jersey" value="${state.profile?.location||''}"><label>Default team</label><select id="team"><option value="">No team yet</option>${state.teams.map(t=>`<option value="${t.id}">${t.name}</option>`).join('')}</select><div class="message good">I understand this app tracks game progress for safety learning, rewards, and team competition.</div><button class="big-button" onclick="saveProfile()">Enter the Yard</button></div></div>`}
window.saveProfile=()=>{const nick=$('#nick').value.trim()||'Safety Sprinter'; const loc=$('#loc').value.trim()||'Home Terminal'; const team=$('#team').value||null; state.profile={email:state.email,nick,location:loc,role:isAdmin()?'admin':'employee'}; state.team=team; state.screen='home'; save(); render()}
function home(){const teamName=state.teams.find(t=>t.id===state.team)?.name||'No team yet'; return `${top('Conrail Safety Sprint',`${state.profile.nick} • ${teamName}`)}<div class="screen"><div class="stats"><div class="stat"><b>${state.streak}</b><span>Day Streak</span></div><div class="stat"><b>${state.tickets}</b><span>Tickets</span></div><div class="stat"><b>${state.points}</b><span>Points</span></div></div><div class="card mission"><h2>Today’s Safety Sprint</h2><p class="small">One minute. Five questions. Safer every day.</p><div class="rail"></div><div class="train">🚂</div><button class="big-button" onclick="startGame('daily')">Start Today’s Sprint</button><button class="button secondary" style="margin-top:12px" onclick="startGame('boss')">Friday Boss Battle</button></div><div class="card"><h3>What’s new in this build</h3><div class="list"><div class="item"><h3>🚸 Crossbuck home-screen icon</h3><p>When saved to your iPhone home screen, the app uses a railroad crossing-style icon.</p></div><div class="item"><h3>👥 Team competitions</h3><p>Admin can enable team mode; employees can create or join teams.</p></div><div class="item"><h3>📘 Rule dictionary</h3><p>Rules are searchable and linked to missed questions for quick education.</p></div></div></div></div>${tabs()}`}
function startGame(mode){const qs=[...state.questions].sort(()=>Math.random()-0.5).slice(0,mode==='boss'?5:5); state.activeGame={mode,idx:0,score:0,correct:0,answers:[],qs,started:Date.now(),answered:false,time:12}; state.screen='game'; save(); render(); startTimer()}
window.startGame=startGame;
let timerInt=null; function startTimer(){clearInterval(timerInt); let left=12; const fill=()=>{const el=$('#timer'); if(el)el.style.width=(left/12*100)+'%'}; fill(); timerInt=setInterval(()=>{if(!state.activeGame||state.activeGame.answered){clearInterval(timerInt);return} left-=.1; if(left<=0){clearInterval(timerInt); choose(-1,12000)} fill()},100)}
function game(){const g=state.activeGame, q=g.qs[g.idx];return `${top(g.mode==='boss'?'Friday Boss Battle':'Daily Safety Sprint',`Question ${g.idx+1} of ${g.qs.length}`)}<div class="screen"><div class="card question-card"><div class="timer-wrap"><div id="timer" class="timer"></div></div><div class="question">${q.question}</div><div class="choices">${q.choices.map((c,i)=>`<button class="choice" id="choice${i}" onclick="choose(${i},${Math.floor(Math.random()*5000)+1200})"><b>${String.fromCharCode(65+i)}.</b> ${c}</button>`).join('')}</div><div id="feedback"></div></div></div>`}
window.choose=(i,ms)=>{const g=state.activeGame;if(!g||g.answered)return;g.answered=true;clearInterval(timerInt);const q=g.qs[g.idx],ok=i===q.correct; if(i>=0)$('#choice'+i)?.classList.add(ok?'correct':'wrong'); $('#choice'+q.correct)?.classList.add('correct'); const pts=ok?100+(ms<5000?50:0):0; g.score+=pts; if(ok)g.correct++; else state.missed.unshift({qid:q.id,ruleId:q.ruleId,when:new Date().toISOString()}); g.answers.push({qid:q.id,selected:i,correct:ok,ms,pts}); $('#feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'✅ Green Signal!':'🚧 Red Signal!'}</b><br>${ok?'Nice move. ':`Correct: ${q.choices[q.correct]}. `}${q.explanation}<br><span class="rule-source" onclick="openRule('${q.ruleId}')">Read rule: ${q.source}</span><br><br><button class="button" onclick="nextQ()">${g.idx===g.qs.length-1?'See Results':'Next Question'}</button></div>`;save()}
window.nextQ=()=>{const g=state.activeGame;if(g.idx<g.qs.length-1){g.idx++;g.answered=false;save();render();startTimer()}else{finishGame()}}
function finishGame(){const g=state.activeGame;state.points+=g.score+(g.correct===g.qs.length?500:0); state.tickets+=1+(g.correct===g.qs.length?1:0)+(g.mode==='boss'?3:0); state.streak=Math.max(1,state.streak+1); state.sessions++; if(g.correct===g.qs.length&&!state.badges.includes('Green Signal'))state.badges.push('Green Signal'); if(state.sessions>=3&&!state.badges.includes('Streak Engine'))state.badges.push('Streak Engine'); if(state.team){const t=state.teams.find(t=>t.id===state.team); if(t)t.points+=g.score} state.leaderboard.push({nick:state.profile.nick,team:state.teams.find(t=>t.id===state.team)?.name||'Solo',points:g.score+Math.floor(Math.random()*200)}); state.screen='results'; save(); render()}
function results(){const g=state.activeGame; return `${top('Sprint Complete!','Tickets earned. Rules learned.')}<div class="screen"><div class="card hero"><h2>${g.correct}/${g.qs.length} Correct</h2><div class="stats"><div class="stat"><b>${g.score}</b><span>Score</span></div><div class="stat"><b>+${1+(g.correct===g.qs.length?1:0)+(g.mode==='boss'?3:0)}</b><span>Tickets</span></div><div class="stat"><b>${state.streak}</b><span>Streak</span></div></div><br><button class="big-button" onclick="startGame('daily')">Play Again</button><button class="button secondary" style="margin-top:12px" onclick="nav('rules')">Review Rule Dictionary</button></div><div class="card"><h3>Missed question review</h3>${state.missed.length?state.missed.slice(0,3).map(m=>{const r=state.rules.find(r=>r.id===m.ruleId);return `<div class="item"><h3>${r?.title||'Rule Review'}</h3><p>${r?.text||''}</p><span class="rule-source" onclick="openRule('${m.ruleId}')">Open rule</span></div>`}).join(''):'<p class="small">No missed questions this round. Green signal all the way.</p>'}</div></div>${tabs()}`}
function teams(){const enabled=state.teamsEnabled;return `${top('Team Competition',enabled?'Crew vs. crew. Friendly fire only.':'Team mode is currently disabled')}<div class="screen"><div class="card"><h2>${enabled?'Team Mode Enabled':'Team Mode Disabled'}</h2><p class="small">Admin controls whether employees can create teams and compete as crews.</p>${enabled?`<label>Create a new team</label><input id="newTeam" placeholder="Example: Blue Signal Crew"><button class="button good" onclick="createTeam()">Create Team</button>`:'<div class="message error">Ask an admin to enable team competitions.</div>'}</div>${enabled?`<div class="card"><h3>Join a team</h3><div class="list">${state.teams.sort((a,b)=>b.points-a.points).map((t,i)=>`<div class="item rank"><div><h3>${i+1}. ${t.name}</h3><p>${t.members} members • Captain: ${t.captain}</p></div><div><strong>${t.points}</strong><br><button class="button secondary" onclick="joinTeam('${t.id}')">Join</button></div></div>`).join('')}</div></div>`:''}${isAdmin()?adminTeamControls():''}</div>${tabs()}`}
function adminTeamControls(){return `<div class="card"><h3>Admin Team Controls</h3><div class="admin-toggle"><div><b>Allow employee-created teams</b><p class="small">Turn this on for crew competitions and weekly team rewards.</p></div><div class="switch ${state.teamsEnabled?'on':''}" onclick="toggleTeams()"></div></div></div>`}
window.createTeam=()=>{if(!state.teamsEnabled)return;const name=$('#newTeam').value.trim(); if(!name)return toast('Enter a team name first.'); const id='t'+Date.now(); state.teams.push({id,name,captain:state.profile.nick,points:0,members:1}); state.team=id; save(); render(); toast('Team created. Your crew is on the board.')}
window.joinTeam=(id)=>{state.team=id; const t=state.teams.find(t=>t.id===id); if(t)t.members++; save(); render(); toast('Joined team: '+(t?.name||''))}
window.toggleTeams=()=>{state.teamsEnabled=!state.teamsEnabled; save(); render()}
function rules(){const q=(state.search||'').toLowerCase(); const rules=state.rules.filter(r=>(r.title+r.category+r.text+r.source).toLowerCase().includes(q)); return `${top('Rule Dictionary','Search. Read. Review what you missed.')}<div class="screen"><div class="search"><input id="ruleSearch" placeholder="Search rules, categories, sources..." value="${state.search||''}" oninput="state.search=this.value;save();render()"></div><div class="card"><h2>Rule Library</h2><p class="small">This section is where conductors, engineers, and managers can look up rules, read explanations, and review missed topics.</p></div><div class="list">${rules.map(r=>`<div class="item"><h3>${r.title}</h3><p><b>${r.category}</b> — ${r.text}</p><span class="rule-source">${r.source}</span></div>`).join('')||'<div class="item"><h3>No matches</h3><p>Try another keyword.</p></div>'}</div></div>${tabs()}`}
window.openRule=(id)=>{state.screen='rules'; const r=state.rules.find(r=>r.id===id); state.search=r?r.title:''; save(); render()}
function board(){const all=[...state.leaderboard,{nick:state.profile.nick,team:state.teams.find(t=>t.id===state.team)?.name||'Solo',points:state.points}].sort((a,b)=>b.points-a.points).slice(0,10);return `${top('Leaderboard','Weekly reset every Monday')}<div class="screen"><div class="card"><h2>Individual Board</h2><div class="list">${all.map((p,i)=>`<div class="item rank"><div><strong>${i+1}. ${p.nick}</strong><p>${p.team}</p></div><b>${p.points}</b></div>`).join('')}</div></div><div class="card"><h2>Team Board</h2><div class="list">${state.teams.sort((a,b)=>b.points-a.points).map((t,i)=>`<div class="item rank"><div><strong>${i+1}. ${t.name}</strong><p>${t.members} members</p></div><b>${t.points}</b></div>`).join('')}</div></div></div>${tabs()}`}
function profile(){return `${top('My Profile','Your crew card')}<div class="screen"><div class="card"><label>Email</label><input value="${mask(state.profile.email)}" disabled><label>Nickname</label><input id="editNick" value="${state.profile.nick}"><label>Location</label><input id="editLoc" value="${state.profile.location}"><button class="button" onclick="updateProfile()">Save Profile</button><button class="button secondary" style="margin-top:10px" onclick="nav('admin')">${isAdmin()?'Open Admin Dashboard':'Admin Locked'}</button><button class="button danger" style="margin-top:10px" onclick="resetDemo()">Reset Demo Data</button></div><div class="badge-grid">${['Green Signal','Streak Engine','Rule Rocket','Team Captain'].map(b=>`<div class="badge ${state.badges.includes(b)?'':'locked'}"><div class="icon">${b==='Green Signal'?'🚦':b==='Streak Engine'?'🔥':b==='Rule Rocket'?'🚀':'👥'}</div><b>${b}</b><p class="small">${state.badges.includes(b)?'Unlocked':'Locked'}</p></div>`).join('')}</div></div>${tabs()}`}
function mask(e){return e.replace(/^(.).+(@.+)$/,'$1***$2')}
window.updateProfile=()=>{state.profile.nick=$('#editNick').value.trim()||state.profile.nick; state.profile.location=$('#editLoc').value.trim()||state.profile.location; save(); render(); toast('Profile saved.')}
window.resetDemo=()=>{localStorage.removeItem(LS);state=defaults();render()}
function admin(){if(!isAdmin())return `${top('Admin Locked','Manager access only')}<div class="screen"><div class="card hero"><h2>Red Signal</h2><p>This area is for approved admin emails only.</p><button class="button" onclick="nav('home')">Back Home</button></div></div>${tabs()}`;return `${top('Admin Dashboard','Controls for teams, content, and reports')}<div class="screen"><div class="card"><h2>Team Function</h2><div class="admin-toggle"><div><b>Enable team competitions</b><p class="small">Employees can create teams, join teams, and compete on the team board.</p></div><div class="switch ${state.teamsEnabled?'on':''}" onclick="toggleTeams()"></div></div></div><div class="card"><h2>Import Questions CSV</h2><p class="small">Use columns: question, choice_a, choice_b, choice_c, choice_d, correct_answer, explanation, category, difficulty, source</p><input type="file" id="csv" accept=".csv"><button class="button" onclick="importCsv()">Import Questions</button></div><div class="card"><h2>Rule Dictionary Manager</h2><p class="small">For now, rule entries are sample data. Next build can add CSV/PDF import for dictionary rules.</p><button class="button secondary" onclick="downloadReport()">Export Demo Report CSV</button></div></div>${tabs()}`}
window.importCsv=()=>{const f=$('#csv').files[0]; if(!f)return toast('Choose a CSV file first.'); const reader=new FileReader(); reader.onload=()=>{const rows=reader.result.split(/\r?\n/).filter(Boolean); const heads=rows.shift().split(',').map(h=>h.trim().replace(/^"|"$/g,'')); let count=0; for(const row of rows){const vals=parseCSV(row); const obj={}; heads.forEach((h,i)=>obj[h]=vals[i]||''); if(obj.question&&obj.choice_a){const rid='r_imp_'+Date.now()+count; const q={id:'q_imp_'+Date.now()+count,question:obj.question,choices:[obj.choice_a,obj.choice_b,obj.choice_c,obj.choice_d],correct:'ABCD'.indexOf((obj.correct_answer||'A').trim().toUpperCase()),explanation:obj.explanation||'',category:obj.category||'Imported',difficulty:obj.difficulty||'Easy',source:obj.source||'Imported CSV',ruleId:rid}; state.questions.push(q); state.rules.push({id:rid,title:obj.source||obj.category||'Imported Rule',category:q.category,text:q.explanation||q.question,source:q.source,related:[q.id]}); count++}} save(); render(); toast(`Imported ${count} questions.`)}; reader.readAsText(f)}
function parseCSV(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){q=!q}else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out.map(v=>v.trim())}
window.downloadReport=()=>{const csv='nickname,email,points,tickets,streak,team\n'+[state.profile.nick,state.profile.email,state.points,state.tickets,state.streak,state.teams.find(t=>t.id===state.team)?.name||'Solo'].join(','); const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='safety-sprint-demo-report.csv';a.click()}
function render(){let html=''; if(!state.profile){html=state.screen==='setup'?setup():login()}else{html=({home,game,results,teams,rules,board,profile,admin}[state.screen]||home)()} app.innerHTML=html}
render();
